### ISSUE TITLE
Better user experience on SDDM

### ISSUE THREAD

**Issue by 34N0** [34N0/pam-authramp#57]
Currently SDDM ignores the PAM messages and only displays "Authentication failed".

**Comment by qoijjj** [comment]
Going to rebase `staging` soon and pull back in pam-authramp and was curious if there's any chance of a fix for this in time for the next round of testing?

**Comment by 34N0** [comment]
I did some testing and current secureblue:latest implementation using the official pam_faillock package causes the exact same behavior. I am guessing this is either a SDDM issue or its by their design. 

I think i'll cut an issue on SDDM.

**Comment by qoijjj** [comment]
I'm not sure if it's related, but the behavior is still pretty broken on KDE Plasma.

Instead of Authentication failed, it now just lets me continuously enter passwords even after using the free tries. The only difference is after the free tries are used, a valid password no longer works.

This isn't something I can merge into `live` for secureblue because the misleading availability of the password text input field could lead to users locking themselves out.

**Comment by qoijjj** [comment]
I can open a new issue for this if needed.

**Comment by qoijjj** [comment]
I've since rebased back so that dir doesn't exist. Let me open a new issue with the repro steps
